### ISSUE TITLE
Roadmap v1.7.0

### ISSUE THREAD

**Issue by Cyrix126** [Cyrix126/gupaxx#27]
# TODO v1.7.0

This release will focus on improving UI, simplifying some features and adding new ones.
#### Common

- [x] Ability to resize height of consoles
- [x] Friendly custom start options interface

#### Tab

- [x] **Status** : add description for load average in Xmrig column
- [x] **Status** : add number of workers in Proxy column
- [x]  **Status**: processes, bottom buttons to hide columns.
- [x] **P2Pool**: title and link to project used in header 
- [x] **P2Pool**: add button "switch to local node if it is ready"
- [x] **Xmrig**  : title and link to project used in header 
- [x] **XvB**   : button to watch p2pool node to account for external HR or using only stratum data

### Internal

- [x] **P2Pool**: Make p2pool restart and use local node if node process status is ready and synced. button enabled by default. Allows using remote node while syncing local node.
- [x] **P2Pool** change state dynamically based on Node connection, p2p connections, synchronization.
- [x] **P2Pool** update bundled version to v4.3
- [x] **XvB**: watch for stratum data by default instead of p2pool node
- [x] update dependencies and fix small breaking change
- [x]  some code cleanup

### Doc
- [x] improve License notices on README and source code

### Fixes
- [x] https://github.com/Cyrix126/gupaxx/issues/52
- [x] https://github.com/Cyrix126/gupaxx/issues/53
- [x] https://github.com/Cyrix126/gupaxx/issues/56
- [x] https://github.com/Cyrix126/gupaxx/issues/57

## Pre-Release

- [x] test

**Comment by Cyrix126** [comment]
Edit: some stuff moved to https://github.com/Cyrix126/gupaxx/issues/29

**Comment by Cyrix126** [comment]
Edit: some stuff moved to  [todo v1.5.4](https://github.com/Cyrix126/gupaxx/issues/50)

**Comment by Cyrix126** [comment]
renamed 1.6.0 to 1.7.0

**Comment by Cyrix126** [comment]
https://github.com/Cyrix126/gupaxx/releases/tag/v1.7.0
