### ISSUE TITLE
Roadmap v1.5.2

### ISSUE THREAD

**Issue by Cyrix126** [Cyrix126/gupaxx#29]
# TODO v.1.5.2

Maintenance release

### Tab
- [x] **Node**  : place toggle buttons on same height
- [x] **Node**  : lower default in/out peers value
- [x] **P2Pool**: "use local node" unchecked by default
- [x] **P2Pool**: remove dead remote nodes 
- [x] **XvB**   : change description of hero mode to reflect new changes on XvB rounds odd selection
## Internal
- [x] increase default p2pool buffer from 5% to 25%
- [x] much more accurate pinging of remote nodes
- [x] update chosen XvB node at start of process 
- [x] update dependencies (one breaking change)
- [x] much better panic message 
## Fixes
- [x] requires a minimum available 1% of time of algo to switch pool (prevent updating xmrig/proxy twice immediately) 
- [x] https://github.com/Cyrix126/gupaxx/issues/19 
- [x] https://github.com/Cyrix126/gupaxx/issues/21 
- [x] https://github.com/Cyrix126/gupaxx/issues/23
- [x] https://github.com/Cyrix126/gupaxx/issues/25
- [x] https://github.com/Cyrix126/gupaxx/issues/26
- [x] https://github.com/Cyrix126/gupaxx/issues/28
- [x] https://github.com/Cyrix126/gupaxx/issues/30
- [x] https://github.com/Cyrix126/gupaxx/issues/31
- [x] https://github.com/Cyrix126/gupaxx/issues/32
- [x] https://github.com/Cyrix126/gupaxx/issues/33
- [x] https://github.com/Cyrix126/gupaxx/issues/34
## Pre-Release
- [x] test

**Comment by Cyrix126** [comment]
closed by release [v1.5.2](https://github.com/Cyrix126/gupaxx/releases/tag/v1.5.2)
