### ISSUE TITLE
ROADMAP v1.5.4

### ISSUE THREAD

**Issue by Cyrix126** [Cyrix126/gupaxx#50]
# TODO v.1.5.4

This release will focus on the UI by making it more usable, coherent and adaptable to different screen ratio.
### Common
- [x] Use fixed size of fonts, do not resize them.
- [x] Rework widgets/fonts for size/spacing/resizing/alignments/responsiveness/coherence on every tabs.
- [x] Rework Top bar
- [x] Rework Bottom bar
- [x] Immediate resizing (remove one second black screen)
- [x] Rework scroll bars
- [x] Rework heading of tab 
### Tab
- [x] **About** : update content of used software.
- [x] **Status**:  display uptime and hashrate vertically to reduce column width.
- [x] **Status**:  human friendly display of hashrate with right metrics.
- [x] **XvB**   : logo and links on single line and centered. 

## Internal
- [x] **Bundle**: bump version of XMRig to 6.22.2
- [x] update xmrig benchmarks
- [x] Improve code about Ui, less complexity, less duplication.
- [x]  better binary optimization 
- [x] update Rust edition to 2024  
- [x]  optimize size of images  (thanks [DeanLemans](https://github.com/DeanLemans))
- [x] deprecate support for mac os 12
## Documentation
- [x] improve grammar and syntax of various doc files (thanks [DeanLemans](https://github.com/DeanLemans))
## Fixes
- [x] https://github.com/Cyrix126/gupaxx/issues/20
- [x] manual XvB HR and manual P2Pool HR mode don't present proxy values when used
- [x] when no shares, time of algo is shown as 0 for one decision.
- [x] when mining all on p2pool, hover text says it will mine on xvb next.
- [x] Status tab, alignments, different size, strange spacing, strange returns of line (fixed after setting fixed size of fonts)  
   #44  
   #45
- [x] Windows wrong size for custom Node DB path  
   #19
- [x] https://github.com/Cyrix126/gupaxx/issues/48

## Pre-Release
- [x] test

**Comment by Cyrix126** [comment]
https://github.com/Cyrix126/gupaxx/releases/tag/v1.5.4

**Comment by Cyrix126** [comment]
renamed from 1.5.4 to 1.6.0
